apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbbot-deployment
  namespace: kbbot
  labels:
    app: kbbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbbot
  template:
    metadata:
      labels:
        app: kbbot
    spec:
      containers:
        - name: kbbot
          image: mikej091/know-bot:latest
          imagePullPolicy: Always
          env:
            - name: DG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: knowbot-token
                  key: discord-token
